version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: terra_hub_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: terrahub
    ports:
      - "5433:5432"
    volumes:
      - terra_hub_data_v2:/var/lib/postgresql/data

volumes:
  terra_hub_data_v2: